define_product_vision:
  agent: product_owner
  description: >
    Define the overarching vision for the product {topic}.
    This involves understanding the target audience, the problem the product solves,
    and the long-term goals for the product's success. This provides a guiding star
    for all development efforts.
  expected_output: >
    A concise and clearly articulated product vision statement.

manage_product_backlog:
  agent: product_owner
  description: >
    Create, maintain, and refine the product backlog.
    This involves capturing all potential features, enhancements, bug fixes, and other
    work items related to the product. The backlog serves as a single source of truth
    for what needs to be built.
  expected_output: >
    An updated and well-organized product backlog containing user stories or backlog items
    with clear descriptions.
  context:
    - define_product_vision
  output_file: output/product_backlog.md

prioritize_backlog_items:
  agent: product_owner
  description: >
    根据业务价值、风险、工作量和依赖关系等因素对产品待办事项进行排序，确保团队优先处理最重要的事项。
  expected_output: >
    一个按相对重要性排序的优先级产品待办事项列表。
  context:
    - manage_product_backlog

make_product_decisions:
  agent: product_owner
  description: >
    根据不断变化的需求和反馈，及时且明智地做出与产品相关的决策，包括范围调整和需求变更。
  expected_output: >
    清晰且文档化的产品相关决策，以指导开发流程。
  human_input: True
